app:
    resource: "@AppBundle/Controller/"
    type:     annotation


admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /avavav

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /avavav

logout:
    path: /logout

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"