<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function findCategories($animal)
    {
        return $this->createQueryBuilder('c')
            ->join('c.animal', 'a')
            ->andWhere('a.titleEng = :animal')
            ->andWhere('c.titleEng <> :none')
            ->setParameters(array(
                'animal'   => $animal,
                'none'     => 'none',
            ))
            ->getQuery()
            ->getResult();
    }
}
